import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react';
import Sidebar from '../components/Sidebar';
import Typography from '@mui/material/Typography';
import Grid from '@mui/material/Grid';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';

// Charts
import VerticalBarChart from '../components/Charts/VerticalBarChart';
import HorizontalBarChart from '../components/Charts/HorizontalBarChart';
import LineChart from '../components/Charts/LineChart';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>SP UI Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar>
        <Grid container direction="row" justifyContent="space-evenly" spacing={4} style={{ paddingBottom: '1rem' }}>

          <Grid
            item
            direction="row"
          >
            <Card sx={{ minWidth: 600 }}>
              <CardContent>
                <Grid container direction="row" spacing={2}>
                  <Grid item>
                    <Typography variant="h6" color='#C32F27'>
                      New Orders
                    </Typography>
                    <Typography variant="subtitle1" color='#D8572A'>
                      223,222
                    </Typography>
                  </Grid>

                  <Grid item>
                    <VerticalBarChart />
                  </Grid>
                </Grid>
              </CardContent>
            </Card>
          </Grid>

          <Grid
            item
            direction="row"
          >
            <Card sx={{ minWidth: 600 }}>
              <CardContent>
                <Grid container direction="row" spacing={2}>
                  <Grid item>
                    <Typography variant="h6" color='#ff638480'>
                      Customer Orders
                    </Typography>
                    <Typography variant="subtitle1" color='#35a2eb80'>
                      Random Numbers
                    </Typography>
                  </Grid>

                  <Grid item>
                    <HorizontalBarChart />
                  </Grid>
                </Grid>
              </CardContent>
            </Card>
          </Grid>

        </Grid>

        <Card sx={{ minWidth: 500 }}>
          <Grid container direction="column" spacing={2} style={{ padding: '1rem' }}>
            <Grid item>
              <Typography variant="h6" color='#B8BAC8'>
                Revenue
              </Typography>
              <Typography variant="subtitle1" color='#AA78A6'>
                Revenue is the income that a business has from its normal business activities,
                usually from the sale of goods and services to customers.
              </Typography>
            </Grid>

            <Grid item>
              <LineChart />
            </Grid>
          </Grid>
        </Card>

      </Sidebar>

      <footer className={styles.footer}>
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </footer>
    </div >
  )
}
